- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes


- name: Delete the Nginx html  
  file:
    path: "{{ project_path }}/html"
    state: absent

- name: Delete the Nginx config
  file:
    path:
      - "{{ config_path }}/sites-enabled/default"
      - "{{ config_path }}/sites-available/default"
    state: absent


- name: Copy Nginx configuration file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Enable and start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
